version: "3.3"
services: 
  db:
    image: postgres:9.6
    container_name: echo-db
    volumes:
      - echo-data:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=echo

volumes:
  echo-data:
    driver: local
